/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KompleksPodKlyuchRouteImport } from './routes/kompleks-pod-klyuch'
import { Route as OhrannayaSignalizaciyaRouteImport } from './routes/ohrannaya-signalizaciya'
import { Route as PozharnayaSignalizaciyaRouteImport } from './routes/pozharnaya-signalizaciya'
import { Route as SkudDomofonyRouteImport } from './routes/skud-domofony'
import { Route as VideonablyudenieRouteImport } from './routes/videonablyudenie'
import { Route as ZayavkaRouteImport } from './routes/zayavka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KompleksPodKlyuchRoute = KompleksPodKlyuchRouteImport.update({
  id: '/kompleks-pod-klyuch',
  path: '/kompleks-pod-klyuch',
  getParentRoute: () => rootRouteImport,
} as any)
const OhrannayaSignalizaciyaRoute = OhrannayaSignalizaciyaRouteImport.update({
  id: '/ohrannaya-signalizaciya',
  path: '/ohrannaya-signalizaciya',
  getParentRoute: () => rootRouteImport,
} as any)
const PozharnayaSignalizaciyaRoute = PozharnayaSignalizaciyaRouteImport.update({
  id: '/pozharnaya-signalizaciya',
  path: '/pozharnaya-signalizaciya',
  getParentRoute: () => rootRouteImport,
} as any)
const SkudDomofonyRoute = SkudDomofonyRouteImport.update({
  id: '/skud-domofony',
  path: '/skud-domofony',
  getParentRoute: () => rootRouteImport,
} as any)
const VideonablyudenieRoute = VideonablyudenieRouteImport.update({
  id: '/videonablyudenie',
  path: '/videonablyudenie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZayavkaRoute = ZayavkaRouteImport.update({
  id: '/zayavka',
  path: '/zayavka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kompleks-pod-klyuch': typeof KompleksPodKlyuchRoute
  '/ohrannaya-signalizaciya': typeof OhrannayaSignalizaciyaRoute
  '/pozharnaya-signalizaciya': typeof PozharnayaSignalizaciyaRoute
  '/skud-domofony': typeof SkudDomofonyRoute
  '/videonablyudenie': typeof VideonablyudenieRoute
  '/zayavka': typeof ZayavkaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kompleks-pod-klyuch': typeof KompleksPodKlyuchRoute
  '/ohrannaya-signalizaciya': typeof OhrannayaSignalizaciyaRoute
  '/pozharnaya-signalizaciya': typeof PozharnayaSignalizaciyaRoute
  '/skud-domofony': typeof SkudDomofonyRoute
  '/videonablyudenie': typeof VideonablyudenieRoute
  '/zayavka': typeof ZayavkaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kompleks-pod-klyuch': typeof KompleksPodKlyuchRoute
  '/ohrannaya-signalizaciya': typeof OhrannayaSignalizaciyaRoute
  '/pozharnaya-signalizaciya': typeof PozharnayaSignalizaciyaRoute
  '/skud-domofony': typeof SkudDomofonyRoute
  '/videonablyudenie': typeof VideonablyudenieRoute
  '/zayavka': typeof ZayavkaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kompleks-pod-klyuch'
    | '/ohrannaya-signalizaciya'
    | '/pozharnaya-signalizaciya'
    | '/skud-domofony'
    | '/videonablyudenie'
    | '/zayavka'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kompleks-pod-klyuch'
    | '/ohrannaya-signalizaciya'
    | '/pozharnaya-signalizaciya'
    | '/skud-domofony'
    | '/videonablyudenie'
    | '/zayavka'
  id:
    | '__root__'
    | '/'
    | '/kompleks-pod-klyuch'
    | '/ohrannaya-signalizaciya'
    | '/pozharnaya-signalizaciya'
    | '/skud-domofony'
    | '/videonablyudenie'
    | '/zayavka'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KompleksPodKlyuchRoute: typeof KompleksPodKlyuchRoute
  OhrannayaSignalizaciyaRoute: typeof OhrannayaSignalizaciyaRoute
  PozharnayaSignalizaciyaRoute: typeof PozharnayaSignalizaciyaRoute
  SkudDomofonyRoute: typeof SkudDomofonyRoute
  VideonablyudenieRoute: typeof VideonablyudenieRoute
  ZayavkaRoute: typeof ZayavkaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kompleks-pod-klyuch': {
      id: '/kompleks-pod-klyuch'
      path: '/kompleks-pod-klyuch'
      fullPath: '/kompleks-pod-klyuch'
      preLoaderRoute: typeof KompleksPodKlyuchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ohrannaya-signalizaciya': {
      id: '/ohrannaya-signalizaciya'
      path: '/ohrannaya-signalizaciya'
      fullPath: '/ohrannaya-signalizaciya'
      preLoaderRoute: typeof OhrannayaSignalizaciyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pozharnaya-signalizaciya': {
      id: '/pozharnaya-signalizaciya'
      path: '/pozharnaya-signalizaciya'
      fullPath: '/pozharnaya-signalizaciya'
      preLoaderRoute: typeof PozharnayaSignalizaciyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skud-domofony': {
      id: '/skud-domofony'
      path: '/skud-domofony'
      fullPath: '/skud-domofony'
      preLoaderRoute: typeof SkudDomofonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videonablyudenie': {
      id: '/videonablyudenie'
      path: '/videonablyudenie'
      fullPath: '/videonablyudenie'
      preLoaderRoute: typeof VideonablyudenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zayavka': {
      id: '/zayavka'
      path: '/zayavka'
      fullPath: '/zayavka'
      preLoaderRoute: typeof ZayavkaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KompleksPodKlyuchRoute: KompleksPodKlyuchRoute,
  OhrannayaSignalizaciyaRoute: OhrannayaSignalizaciyaRoute,
  PozharnayaSignalizaciyaRoute: PozharnayaSignalizaciyaRoute,
  SkudDomofonyRoute: SkudDomofonyRoute,
  VideonablyudenieRoute: VideonablyudenieRoute,
  ZayavkaRoute: ZayavkaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
